export const db = {
    Frameworks: [
        {
            id: 0,
            name: 'sinon-express-mock',
            url: 'https://www.npmjs.com/package/sinon-express-mock',
            categories: [2],
        },
        {
            id: 1,
            name: 'nightwatch',
            url: 'https://www.npmjs.com/package/nightwatch',
            categories: [3],
        },
        {
            id: 2,
            name: 'nightwatch-helpers',
            url: 'https://www.npmjs.com/package/nightwatch-helpers',
            categories: [3],
        },
        {
            id: 3,
            name: 'selenium-server',
            url: 'https://www.npmjs.com/package/selenium-server',
            categories: [3],
        },
        {
            id: 4,
            name: 'jest-environment-jsdom-sixteen',
            url: 'https://www.npmjs.com/package/jest-environment-jsdom-sixteen',
            categories: [1, 12],
        },
        {
            id: 5,
            name: 'hammer-simulator',
            url: 'https://www.npmjs.com/package/hammer-simulator',
            categories: [5, 7],
        },
        {
            id: 6,
            name: 'karma-coverage-istanbul-reporter',
            url:
                'https://www.npmjs.com/package/karma-coverage-istanbul-reporter',
            categories: [6],
        },
        {
            id: 7,
            name: 'karma-detect-browsers',
            url: 'https://www.npmjs.com/package/karma-detect-browsers',
            categories: [9, 10, 11, 16],
        },
        {
            id: 8,
            name: '@testing-library/user-event',
            url: 'https://www.npmjs.com/package/@testing-library/user-event',
            categories: [4, 9],
        },
        {
            id: 9,
            name: 'grunt-mocha-test',
            url: 'https://www.npmjs.com/package/grunt-mocha-test',
            categories: [8, 10, 16],
        },
        {
            id: 10,
            name: 'karma-jasmine-ajax',
            url: 'https://www.npmjs.com/package/karma-jasmine-ajax',
            categories: [2],
        },
        {
            id: 11,
            name: 'karma-opera-launcher',
            url: 'https://www.npmjs.com/package/karma-opera-launcher',
            categories: [9, 10, 11, 16],
        },
        {
            id: 12,
            name: '@testing-library/dom',
            url: 'https://www.npmjs.com/package/@testing-library/dom',
            categories: [12],
        },
        {
            id: 13,
            name: '@types/chai-dom',
            url: 'https://www.npmjs.com/package/@types/chai-dom',
            categories: [12],
        },
        {
            id: 14,
            name: '@types/enzyme',
            url: 'https://www.npmjs.com/package/@types/enzyme',
            categories: [13],
        },
        {
            id: 15,
            name: '@types/sinon',
            url: 'https://www.npmjs.com/package/@types/sinon',
            categories: [2],
        },
        {
            id: 16,
            name: 'chai-dom',
            url: 'https://www.npmjs.com/package/chai-dom',
            categories: [12],
        },
        {
            id: 17,
            name: 'expect-puppeteer',
            url: 'https://www.npmjs.com/package/expect-puppeteer',
            categories: [15],
        },
        {
            id: 18,
            name: 'vrtest-mui',
            url: 'https://www.npmjs.com/package/vrtest-mui',
            categories: [12],
        },
        {
            id: 19,
            name: 'karma-script-launcher',
            url: 'https://www.npmjs.com/package/karma-script-launcher',
            categories: [8, 9, 10, 11],
        },
        {
            id: 20,
            name: 'karma-spec-reporter',
            url: 'https://www.npmjs.com/package/karma-spec-reporter',
            categories: [14],
        },
        {
            id: 21,
            name: 'karma-jsdom-launcher',
            url: 'https://www.npmjs.com/package/karma-jsdom-launcher',
            categories: [9, 11],
        },
        {
            id: 22,
            name: 'testswarm',
            url: 'https://www.npmjs.com/package/testswarm',
            categories: [0],
        },
        {
            id: 23,
            name: 'node-qunit-puppeteer',
            url: 'https://www.npmjs.com/package/node-qunit-puppeteer',
            categories: [1],
        },
        {
            id: 24,
            name: 'jasmine-json',
            url: 'https://www.npmjs.com/package/jasmine-json',
            categories: [1, 8],
        },
        {
            id: 25,
            name: 'jasmine-tagged',
            url: 'https://www.npmjs.com/package/jasmine-tagged',
            categories: [1, 8],
        },
        {
            id: 26,
            name: 'mocha-multi-reporters',
            url: 'https://www.npmjs.com/package/mocha-multi-reporters',
            categories: [14],
        },
        {
            id: 27,
            name: 'mock-spawn',
            url: 'https://www.npmjs.com/package/mock-spawn',
            categories: [2],
        },
        {
            id: 28,
            name: 'selenium-standalone',
            url: 'https://www.npmjs.com/package/selenium-standalone',
            categories: [3],
        },
        {
            id: 29,
            name: 'expect.js',
            url: 'https://www.npmjs.com/package/expect.js',
            categories: [15],
        },
        {
            id: 30,
            name: 'karma-safari-private-launcher',
            url: 'https://www.npmjs.com/package/karma-safari-private-launcher',
            categories: [9, 10, 11],
        },
        {
            id: 31,
            name: 'jest-environment-jsdom-fourteen',
            url:
                'https://www.npmjs.com/package/jest-environment-jsdom-fourteen',
            categories: [1, 12],
        },
        {
            id: 32,
            name: 'jest-serializer-path',
            url: 'https://www.npmjs.com/package/jest-serializer-path',
            categories: [0],
        },
        {
            id: 33,
            name: 'jest-silent-reporter',
            url: 'https://www.npmjs.com/package/jest-silent-reporter',
            categories: [14],
        },
        {
            id: 34,
            name: 'ts-jest',
            url: 'https://www.npmjs.com/package/ts-jest',
            categories: [1],
        },
        {
            id: 35,
            name: 'markdown-doctest',
            url: 'https://www.npmjs.com/package/markdown-doctest',
            categories: [17],
        },
        {
            id: 36,
            name: 'qunit-extras',
            url: 'https://www.npmjs.com/package/qunit-extras',
            categories: [1, 8],
        },
        {
            id: 37,
            name: 'node-qunit',
            url: 'https://www.npmjs.com/package/node-qunit',
            categories: [1, 6],
        },
        {
            id: 38,
            name: 'assert',
            url: 'https://www.npmjs.com/package/assert',
            categories: [15],
        },
        {
            id: 39,
            name: 'jest-canvas-mock',
            url: 'https://www.npmjs.com/package/jest-canvas-mock',
            categories: [2],
        },
        {
            id: 40,
            name: 'mock-stdin',
            url: 'https://www.npmjs.com/package/mock-stdin',
            categories: [2],
        },
        {
            id: 41,
            name: 'jasmine-jquery',
            url: 'https://www.npmjs.com/package/jasmine-jquery',
            categories: [1, 12],
        },
        {
            id: 42,
            name: 'jest-snapshot-serializer-ansi',
            url: 'https://www.npmjs.com/package/jest-snapshot-serializer-ansi',
            categories: [1, 12],
        },
        {
            id: 43,
            name: 'jest-watch-typeahead',
            url: 'https://www.npmjs.com/package/jest-watch-typeahead',
            categories: [0],
        },
        {
            id: 44,
            name: 'test262-stream',
            url: 'https://www.npmjs.com/package/test262-stream',
            categories: [0],
        },
        {
            id: 45,
            name: '@serverless/test',
            url: 'https://www.npmjs.com/package/@serverless/test',
            categories: [14],
        },
        {
            id: 46,
            name: 'chai-as-promised',
            url: 'https://www.npmjs.com/package/chai-as-promised',
            categories: [15],
        },
        {
            id: 47,
            name: 'syn',
            url: 'https://www.npmjs.com/package/syn',
            categories: [4, 9],
        },
        {
            id: 48,
            name: 'grunt-mocha-cli',
            url: 'https://www.npmjs.com/package/grunt-mocha-cli',
            categories: [8, 10],
        },
        {
            id: 49,
            name: 'mock-knex',
            url: 'https://www.npmjs.com/package/mock-knex',
            categories: [2],
        },
        {
            id: 50,
            name: 'nock',
            url: 'https://www.npmjs.com/package/nock',
            categories: [2],
        },
        {
            id: 51,
            name: 'expect',
            url: 'https://www.npmjs.com/package/expect',
            categories: [15],
        },
        {
            id: 52,
            name: 'grunt-jasmine-node',
            url: 'https://www.npmjs.com/package/grunt-jasmine-node',
            categories: [1, 8],
        },
        {
            id: 53,
            name: 'grunt-template-jasmine-requirejs',
            url:
                'https://www.npmjs.com/package/grunt-template-jasmine-requirejs',
            categories: [1, 8],
        },
        {
            id: 54,
            name: '@percy/cypress',
            url: 'https://www.npmjs.com/package/@percy/cypress',
            categories: [3, 9, 12],
        },
        {
            id: 55,
            name: 'jest-image-snapshot',
            url: 'https://www.npmjs.com/package/jest-image-snapshot',
            categories: [1, 12],
        },
        {
            id: 56,
            name: 'mm',
            url: 'https://www.npmjs.com/package/mm',
            categories: [2],
        },
        {
            id: 57,
            name: '@vue/server-test-utils',
            url: 'https://www.npmjs.com/package/@vue/server-test-utils',
            categories: [1, 12],
        },
        {
            id: 58,
            name: 'puppeteer-core',
            url: 'https://www.npmjs.com/package/puppeteer-core',
            categories: [4, 9],
        },
        {
            id: 59,
            name: 'videojs-generate-karma-config',
            url: 'https://www.npmjs.com/package/videojs-generate-karma-config',
            categories: [9, 11],
        },
        {
            id: 60,
            name: 'karma-chai',
            url: 'https://www.npmjs.com/package/karma-chai',
            categories: [15],
        },
        {
            id: 61,
            name: 'happen',
            url: 'https://www.npmjs.com/package/happen',
            categories: [4, 9],
        },
        {
            id: 62,
            name: 'karma-expect',
            url: 'https://www.npmjs.com/package/karma-expect',
            categories: [15],
        },
        {
            id: 63,
            name: 'prosthetic-hand',
            url: 'https://www.npmjs.com/package/prosthetic-hand',
            categories: [4, 9],
        },
        {
            id: 64,
            name: '@swc-node/jest',
            url: 'https://www.npmjs.com/package/@swc-node/jest',
            categories: [0],
        },
        {
            id: 65,
            name: 'axios-mock-adapter',
            url: 'https://www.npmjs.com/package/axios-mock-adapter',
            categories: [2],
        },
        {
            id: 66,
            name: 'mockdate',
            url: 'https://www.npmjs.com/package/mockdate',
            categories: [2],
        },
        {
            id: 67,
            name: 'chai-datetime',
            url: 'https://www.npmjs.com/package/chai-datetime',
            categories: [15],
        },
        {
            id: 68,
            name: 'chai-spies',
            url: 'https://www.npmjs.com/package/chai-spies',
            categories: [15],
        },
        {
            id: 69,
            name: 'mongo-unit',
            url: 'https://www.npmjs.com/package/mongo-unit',
            categories: [1],
        },
        {
            id: 70,
            name: 'karma-chai-sinon',
            url: 'https://www.npmjs.com/package/karma-chai-sinon',
            categories: [2, 15],
        },
        {
            id: 71,
            name: 'geckodriver',
            url: 'https://www.npmjs.com/package/geckodriver',
            categories: [4, 9],
        },
        {
            id: 72,
            name: 'react-testing-library',
            url: 'https://www.npmjs.com/package/react-testing-library',
            categories: [13],
        },
        {
            id: 73,
            name: 'qunit-cli',
            url: 'https://www.npmjs.com/package/qunit-cli',
            categories: [1],
        },
        {
            id: 74,
            name: '@applitools/eyes-cypress',
            url: 'https://www.npmjs.com/package/@applitools/eyes-cypress',
            categories: [3],
        },
        {
            id: 75,
            name: 'karma-cli',
            url: 'https://www.npmjs.com/package/karma-cli',
            categories: [8, 9, 10, 11],
        },
        {
            id: 76,
            name: 'karma-tap',
            url: 'https://www.npmjs.com/package/karma-tap',
            categories: [1],
        },
        {
            id: 77,
            name: 'casperjs',
            url: 'https://www.npmjs.com/package/casperjs',
            categories: [4, 9],
        },
        {
            id: 78,
            name: 'grunt-contrib-qunit',
            url: 'https://www.npmjs.com/package/grunt-contrib-qunit',
            categories: [1, 9],
        },
        {
            id: 79,
            name: 'mocha-headless-chrome',
            url: 'https://www.npmjs.com/package/mocha-headless-chrome',
            categories: [9, 11, 16],
        },
        {
            id: 80,
            name: 'browserstacktunnel-wrapper',
            url: 'https://www.npmjs.com/package/browserstacktunnel-wrapper',
            categories: [4, 5, 7, 9],
        },
        {
            id: 81,
            name: 'sauce-connect',
            url: 'https://www.npmjs.com/package/sauce-connect',
            categories: [7, 9],
        },
        {
            id: 82,
            name: 'browserstack-local',
            url: 'https://www.npmjs.com/package/browserstack-local',
            categories: [4, 5, 7, 9],
        },
        {
            id: 83,
            name: 'jasmine-check',
            url: 'https://www.npmjs.com/package/jasmine-check',
            categories: [1, 8, 16],
        },
        {
            id: 84,
            name: 'jest-diff',
            url: 'https://www.npmjs.com/package/jest-diff',
            categories: [1, 12],
        },
        {
            id: 85,
            name: 'jest-snapshot-serializer-raw',
            url: 'https://www.npmjs.com/package/jest-snapshot-serializer-raw',
            categories: [1, 12],
        },
        {
            id: 86,
            name: 'karma-jasmine-html-reporter',
            url: 'https://www.npmjs.com/package/karma-jasmine-html-reporter',
            categories: [14],
        },
        {
            id: 87,
            name: '@testing-library/jest-dom',
            url: 'https://www.npmjs.com/package/@testing-library/jest-dom',
            categories: [1, 12],
        },
        {
            id: 88,
            name: '@testing-library/react-hooks',
            url: 'https://www.npmjs.com/package/@testing-library/react-hooks',
            categories: [13],
        },
        {
            id: 89,
            name: 'babel-plugin-tester',
            url: 'https://www.npmjs.com/package/babel-plugin-tester',
            categories: [1, 8],
        },
        {
            id: 90,
            name: 'enzyme',
            url: 'https://www.npmjs.com/package/enzyme',
            categories: [13],
        },
        {
            id: 91,
            name: 'enzyme-adapter-react-16',
            url: 'https://www.npmjs.com/package/enzyme-adapter-react-16',
            categories: [13],
        },
        {
            id: 92,
            name: 'jasmine-node',
            url: 'https://www.npmjs.com/package/jasmine-node',
            categories: [1, 8, 16],
        },
        {
            id: 93,
            name: 'jasmine-reporters',
            url: 'https://www.npmjs.com/package/jasmine-reporters',
            categories: [14],
        },
        {
            id: 94,
            name: 'karma-junit-reporter',
            url: 'https://www.npmjs.com/package/karma-junit-reporter',
            categories: [14],
        },
        {
            id: 95,
            name: 'promises-aplus-tests',
            url: 'https://www.npmjs.com/package/promises-aplus-tests',
            categories: [1, 8],
        },
        {
            id: 96,
            name: 'selenium-webdriver',
            url: 'https://www.npmjs.com/package/selenium-webdriver',
            categories: [3],
        },
        {
            id: 97,
            name: 'jest-junit',
            url: 'https://www.npmjs.com/package/jest-junit',
            categories: [14],
        },
        {
            id: 98,
            name: 'mocha-junit-reporter',
            url: 'https://www.npmjs.com/package/mocha-junit-reporter',
            categories: [14],
        },
        {
            id: 99,
            name: 'jest-circus',
            url: 'https://www.npmjs.com/package/jest-circus',
            categories: [12],
        },
        {
            id: 100,
            name: 'fresh',
            url: 'https://www.npmjs.com/package/fresh',
            categories: [0],
        },
        {
            id: 101,
            name: 'qunitjs',
            url: 'https://www.npmjs.com/package/qunitjs',
            categories: [1, 8],
        },
        {
            id: 102,
            name: 'grunt-contrib-jasmine',
            url: 'https://www.npmjs.com/package/grunt-contrib-jasmine',
            categories: [1, 8, 12, 16],
        },
        {
            id: 103,
            name: 'mock-require',
            url: 'https://www.npmjs.com/package/mock-require',
            categories: [2],
        },
        {
            id: 104,
            name: '@vue/test-utils',
            url: 'https://www.npmjs.com/package/@vue/test-utils',
            categories: [1, 9],
        },
        {
            id: 105,
            name: 'jest-styled-components',
            url: 'https://www.npmjs.com/package/jest-styled-components',
            categories: [1, 12],
        },
        {
            id: 106,
            name: 'jest-dom',
            url: 'https://www.npmjs.com/package/jest-dom',
            categories: [1, 12],
        },
        {
            id: 107,
            name: 'karma-browserify',
            url: 'https://www.npmjs.com/package/karma-browserify',
            categories: [18],
        },
        {
            id: 108,
            name: 'codecov.io',
            url: 'https://www.npmjs.com/package/codecov.io',
            categories: [6],
        },
        {
            id: 109,
            name: 'codecov',
            url: 'https://www.npmjs.com/package/codecov',
            categories: [6],
        },
        {
            id: 110,
            name: 'start-server-and-test',
            url: 'https://www.npmjs.com/package/start-server-and-test',
            categories: [10],
        },
        {
            id: 111,
            name: 'danger',
            url: 'https://www.npmjs.com/package/danger',
            categories: [1],
        },
        {
            id: 112,
            name: 'karma-rollup-preprocessor',
            url: 'https://www.npmjs.com/package/karma-rollup-preprocessor',
            categories: [18],
        },
        {
            id: 113,
            name: '@testing-library/react',
            url: 'https://www.npmjs.com/package/@testing-library/react',
            categories: [13],
        },
        {
            id: 114,
            name: 'grunt-karma',
            url: 'https://www.npmjs.com/package/grunt-karma',
            categories: [8, 9, 10, 11, 16],
        },
        {
            id: 115,
            name: '@types/chai',
            url: 'https://www.npmjs.com/package/@types/chai',
            categories: [15],
        },
        {
            id: 116,
            name: 'karma-ie-launcher',
            url: 'https://www.npmjs.com/package/karma-ie-launcher',
            categories: [9, 10, 11, 16],
        },
        {
            id: 117,
            name: 'rewire',
            url: 'https://www.npmjs.com/package/rewire',
            categories: [1],
        },
        {
            id: 118,
            name: 'sinon-chai',
            url: 'https://www.npmjs.com/package/sinon-chai',
            categories: [15],
        },
        {
            id: 119,
            name: 'karma-mocha-reporter',
            url: 'https://www.npmjs.com/package/karma-mocha-reporter',
            categories: [8, 14],
        },
        {
            id: 120,
            name: 'karma-phantomjs-launcher',
            url: 'https://www.npmjs.com/package/karma-phantomjs-launcher',
            categories: [9, 10, 11, 16],
        },
        {
            id: 121,
            name: 'karma-sourcemap-loader',
            url: 'https://www.npmjs.com/package/karma-sourcemap-loader',
            categories: [18],
        },
        {
            id: 122,
            name: 'karma-browserstack-launcher',
            url: 'https://www.npmjs.com/package/karma-browserstack-launcher',
            categories: [9, 11, 16],
        },
        {
            id: 123,
            name: '@types/jest',
            url: 'https://www.npmjs.com/package/@types/jest',
            categories: [1, 2, 10, 12],
        },
        {
            id: 124,
            name: 'karma-sinon',
            url: 'https://www.npmjs.com/package/karma-sinon',
            categories: [2],
        },
        {
            id: 125,
            name: 'react-test-renderer',
            url: 'https://www.npmjs.com/package/react-test-renderer',
            categories: [13],
        },
        {
            id: 126,
            name: 'karma-edge-launcher',
            url: 'https://www.npmjs.com/package/karma-edge-launcher',
            categories: [9, 10, 11, 16],
        },
        {
            id: 127,
            name: 'should',
            url: 'https://www.npmjs.com/package/should',
            categories: [15],
        },
        {
            id: 128,
            name: 'proxyquire',
            url: 'https://www.npmjs.com/package/proxyquire',
            categories: [1],
        },
        {
            id: 129,
            name: 'cypress',
            url: 'https://www.npmjs.com/package/cypress',
            categories: [3],
        },
        {
            id: 130,
            name: 'karma-safari-launcher',
            url: 'https://www.npmjs.com/package/karma-safari-launcher',
            categories: [9, 10, 11, 16],
        },
        {
            id: 131,
            name: 'jest-cli',
            url: 'https://www.npmjs.com/package/jest-cli',
            categories: [1, 10, 12],
        },
        {
            id: 132,
            name: '@types/mocha',
            url: 'https://www.npmjs.com/package/@types/mocha',
            categories: [9, 11, 16],
        },
        {
            id: 133,
            name: 'karma-mocha',
            url: 'https://www.npmjs.com/package/karma-mocha',
            categories: [9, 10, 11, 16],
        },
        {
            id: 134,
            name: 'karma-qunit',
            url: 'https://www.npmjs.com/package/karma-qunit',
            categories: [1, 8, 9, 10, 11, 16],
        },
        {
            id: 135,
            name: 'jasmine',
            url: 'https://www.npmjs.com/package/jasmine',
            categories: [1, 8, 12, 16],
        },
        {
            id: 136,
            name: 'jasmine-core',
            url: 'https://www.npmjs.com/package/jasmine-core',
            categories: [1, 8, 12, 16],
        },
        {
            id: 137,
            name: 'karma-coverage',
            url: 'https://www.npmjs.com/package/karma-coverage',
            categories: [6],
        },
        {
            id: 138,
            name: 'qunit',
            url: 'https://www.npmjs.com/package/qunit',
            categories: [8],
        },
        {
            id: 139,
            name: 'karma-jasmine',
            url: 'https://www.npmjs.com/package/karma-jasmine',
            categories: [1, 8, 16],
        },
        {
            id: 140,
            name: 'supertest',
            url: 'https://www.npmjs.com/package/supertest',
            categories: [15],
        },
        {
            id: 141,
            name: 'karma-sauce-launcher',
            url: 'https://www.npmjs.com/package/karma-sauce-launcher',
            categories: [7, 9, 11, 16],
        },
        {
            id: 142,
            name: 'puppeteer',
            url: 'https://www.npmjs.com/package/puppeteer',
            categories: [4],
        },
        {
            id: 143,
            name: 'babel-jest',
            url: 'https://www.npmjs.com/package/babel-jest',
            categories: [1, 8, 12],
        },
        {
            id: 144,
            name: 'karma-firefox-launcher',
            url: 'https://www.npmjs.com/package/karma-firefox-launcher',
            categories: [9, 10, 11],
        },
        {
            id: 145,
            name: 'chai',
            url: 'https://www.npmjs.com/package/chai',
            categories: [15],
        },
        {
            id: 146,
            name: 'karma-chrome-launcher',
            url: 'https://www.npmjs.com/package/karma-chrome-launcher',
            categories: [9, 10, 11],
        },
        {
            id: 147,
            name: 'coveralls',
            url: 'https://www.npmjs.com/package/coveralls',
            categories: [6],
        },
        {
            id: 148,
            name: 'sinon',
            url: 'https://www.npmjs.com/package/sinon',
            categories: [2],
        },
        {
            id: 149,
            name: 'karma',
            url: 'https://www.npmjs.com/package/karma',
            categories: [8, 9, 10, 11, 16],
        },
        {
            id: 150,
            name: 'jest',
            url: 'https://www.npmjs.com/package/jest',
            categories: [1, 2, 8, 12],
        },
        {
            id: 151,
            name: 'mocha',
            url: 'https://www.npmjs.com/package/mocha',
            categories: [1, 8, 9, 16],
        },
    ],
    Categories: [
        {
            id: 0,
            name: 'Others',
        },
        {
            id: 1,
            name: 'Unit-Testing',
            description:
                'Testes de unidade tem como objetivo verificar automaticamente pequenas partes do código de forma isolada. De forma simplificada, um teste de unidade chama um método do programa, e verifica se ele retorna o resultado esperado. Frameworks desta categoria são ferramentas para auxiliar no desenvolvimento e execução de testes de unidades, fornecendo uma base para implementação, executando o conjunto de testes e reportando os resultados. Os frameworks dessa categoria buscam automatizar estas tarefas.',
        },
        {
            id: 2,
            name: 'Mock',
            description:
                'Na prática de mock, substitui-se uma parte de código com um objeto que emula a sua funcionalidade real, porém de forma simplificada e sem duplicar sua implementação. Ela se faz muito necessária ao testar frações de código que não são triviais o suficiente para serem testadas de forma isolada. Utilizar mocks é uma boa saída para evitar escrever testes complexos, incompletos e de difícil compreensão. Eles simplificam a estrutura dos teste e ajudam a garantir o seu isolamento. Os frameworks dessa categoria tem como objetivo simular o comportamento de um objeto, função ou funcionalidades de outras bibliotecas para melhor isolar um teste de unidade.',
        },
        {
            id: 3,
            name: 'End-To-End',
            description:
                'Testes fim-a-fim, também chamados de funcionais, são um tipo de teste de software que verifica um sistema sobre suas especificações. Seu objetivo é validar como todos os componentes de um sistema estão funcionando num ambiente próximo ao de produção, sem isolar ou simular elementos externos. Esse tipo de teste requer mais tempo e é mais custoso, sendo comumente realizado pelo cliente ou por desenvolvedores. Todavia, existem frameworks que conseguem automatizá-los. Os frameworks dessa categoria ajudam a testar todo o fluxo de uma aplicação, da mesma maneira que seria utilizada por um usuário.',
        },
        {
            id: 4,
            name: 'Web-Browser-Automation',
            description:
                'Produzir testes unitários para uma aplicação web inclui verificar se a interface do usuário está se comportando de maneira adequada. Para isso, deve-se garantir que as ações tomadas por um usuário durante o uso provocarão mudanças esperadas no fluxo de execução do programa. É possível simular essas ações - cliques, entradas de teclado, upload de arquivos - com código. Os frameworks dessa categoria emulam essas ações para auxiliar na criação de testes baseados na interface de uma aplicação web.',
        },
        {
            id: 5,
            name: 'Mobile-Automation',
            description:
                'Da mesma forma que é possível simular ações de usuário numa aplicação web, o mesmo pode ser feito num aplicativo de celular. A forma que o usuário interage com o programa é muito simular, mas existem fatores - como diferentes sistemas operacionais e presença de sensores de toque - que tornam a tarefa ainda mais complexa. Assim como na categoria anterior, esses frameworks buscam simular entradas de usuário, porém, nesse caso, para aplicativos móveis.',
        },
        {
            id: 6,
            name: 'Code-Covarage',
            description:
                'Cobertura de código representa a porcentagem de linhas executadas de um programa após sua execução. Em teste de software, isso é utilizado para garantir que uma parte significativa do código de uma aplicação tenha sido validada por testes ao menos uma vez. Essa métrica é comumente utilizada para medir a qualidade dos testes. Os frameworks dessa categoria procuram mostrar para o desenvolvedor esse percentual.',
        },
        {
            id: 7,
            name: 'Mobile-Testing',
            description:
                'Testes de aplicações móveis englobam uma grande variedade devido à complexidade desses programas. Esta categoria deve conter os vários tipos de frameworks de teste: para aplicações nativas - desenvolvidas especificamente para determinado sistema operacional; para aplicações híbridas - que são desenvolvidas em uma mesma linguagem de programação para ambos sistemas operacionais; para aplicações web para mobile; para a interface do usuário, entre outras. Nela, os frameworks devem ser capazes de garantir comportamento, performance, qualidade do serviço, mobilidade, usabilidade, interoperabilidade, conectividade, segurança e privacidade por meio da criação e/ou execução de testes.',
        },
        {
            id: 8,
            name: 'Server-Testing',
            description:
                'Teste do lado do servidor englobam todos os possíveis testes voltados para o back-end, de menor granularidade como testes de unidade, a testes de integração com banco de dados, outras APIs e requisições para o front-end. Essa categoria contém frameworks que testam essas funcionalidades.',
        },
        {
            id: 9,
            name: 'Web-Application-Testing',
            description:
                'A descrição de testes para aplicações web se assemelha muito à de testes de aplicações móveis devido à natureza complexa de seu ambiente. Esses modelos de teste verificam a estrutura e comportamento da aplicação, auxiliando na sua criação e execução de seus testes. Os frameworks dessa categoria são ferramentas para facilitar esse processo.',
        },
        {
            id: 10,
            name: 'Server-Runner',
            description:
                'Um test runner é um software capaz de executar de forma automatizada o conjunto de testes desenvolvido para uma aplicação. Portanto, um test runner voltado para o ambiente de servidor visa a execução dos testes produzidos para verificação deste ambiente. Eles buscam um diretório de código, seus respectivos testes e configurações, e executam-os, exibindo seus resultados em um terminal ou um arquivos de log.',
        },
        {
            id: 11,
            name: 'Web-Browser-Runner',
            description:
                'Como em Server-Runner, esta categoria também é uma espécie de test runner. Da mesma maneira, ele executa o conjunto de testes, mas neste caso, para o ambiente web, abrindo um navegador para a execução dos testes.',
        },
        {
            id: 12,
            name: 'DOM-Testing',
            description:
                'DOM - Document Object Model - é uma interface que representa a forma como arquivos HTML e XML são lidos. Ele é utilizado pelo navegador para interpretar a parte visual de uma aplicação. Destarte, testes de DOM visam verificar se os elementos visuais da página estão de acordo com sua especificação. Vários atributos podem ser verificados neste tipo de teste, como por exemplo, cores, dimensões de elementos e suas posições dentro da página, fontes, entre outros.',
        },
        {
            id: 13,
            name: 'React-DOM',
            description:
                'O React é um framework JavaScript para criar interfaces de usuário para aplicações web. Ele é um framework tão relevante e difundido que diversas outras bibliotecas foram criadas para ele, a fim de compartilhar código dentro da comunidade, estender suas funcionalidades e melhorar de uma forma geral o processo de desenvolvimento. Assim como na categoria de DOM-Testing, o objetivo dos frameworks dessa categoria é fazer a verificação dos elementos visuais da sua interface.',
        },
        {
            id: 14,
            name: 'Reporters',
            description:
                'Um bom teste de software deve informar ao desenvolvedor o seu resultado de forma clara. Especialmente em casos de falha, é necessário que seja fácil compreender onde ela ocorreu e qual motivo a causou. Isso facilita o diagnóstico e correção do código. Os frameworks dessa buscam reportar o resultado dos testes de maneira eficiente e automatizada.',
        },
        {
            id: 15,
            name: 'Assertion',
            description:
                'Em um teste de software, asserção é a avaliação binária da verificação do teste. Ela indica True no caso dele ter sido bem sucedido e False, caso contrário. A asserção é importante para a localização de falhas no código. Os frameworks desta categoria auxiliam nessa tarefa. Em geral, eles facilitam a implementação dessa verificação com diversas funções chamadas matchers, nas quais pode-se testar a validade de uma resposta das mais diversas maneiras.',
        },
        {
            id: 16,
            name: 'BDD',
            description:
                'BDD - Behaviour Driven Development - é um processo de desenvolvimento ágil que encoraja a contribuição entre desenvolvedores, analistas de qualidade e profissionais de áreas não-técnicas num projeto de software. Ele busca criar testes que cumpram critérios de validação, de acordo com os interesses de negócios. Desta maneira, estes frameworks ajudam na criação e execução de testes que examinam se o código trabalha corretamente para a entregar o comportamento esperado.',
        },
        {
            id: 17,
            name: 'Documentation-Testing',
            description:
                'É muito comum que softwares tenham seu comportamento ou características explicadas por meio de documentações, a fim de retratar a sua utilidade e funcionamento de forma clara, seja para quem for realizar sua manutenção ou para seus usuários finais. O teste de documentação faz parte da categoria de testes não funcionais e é responsável, justamente, por averiguar se esse comportamento ou características retratam, de fato, o software documentado. O framework dessa categoria visa testar o código em markdown das documentações.',
        },
        {
            id: 18,
            name: 'Framework-Integration',
            description:
                'Como dito anteriormente, existem diversos frameworks para sistemas JavaScript. Um projeto que utiliza um ou mais frameworks deve garantir que essa integração está funcionando de acordo com o esperado. Quando trabalhamos com código externo, é possível que falhas ocorram no âmbito do qualidade (performance, segurança, escalabilidade, etc) do lado da aplicação, dos serviços utilizados por ela e/ou na interação entre elas. Os frameworks dessa categoria visam verificar se essas integrações estão apresentando o comportamento correto.',
        },
    ],
};
